declare const __SERVICE_WORKER_ACTIVE__: boolean
declare const __IS_DEV__: boolean
declare const __IS_PROD__: boolean
declare const __PUBLIC_PATH__: string
declare const __BOOTSTRAP_IMPORT_BUNDLE__: boolean
declare const __EXPOSE_COMPONENTS__: boolean
declare const __PUSH_ENABLED__: boolean
declare const __PUSH_VAPID_KEY_ENDPOINT__: string
declare const __PUSH_REGISTER_ENDPOINT__: string
