# See https://www.netlify.com/docs/netlify-toml-reference/

[build]
  base = "" # Root directory
  publish = "dist"
  command = "yarn build"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
